#!/usr/local/bin/python3

import argparse

from remote.context import Context

context = Context()


def generate(args):
    from student.utils import generate_students

    file_path = args.file_path
    students = generate_students(file_path)
    context.organization.create_repositories(students)


parser = argparse.ArgumentParser(
    prog="glm",
    description="Git learning management system",
    )
subparsers = parser.add_subparsers()

# generate subparser
generate_parser = subparsers.add_parser("generate", help='''
    Command for generating students
''')
generate_parser.add_argument("file_path", action="store", type=str, help="file for generating students")
generate_parser.set_defaults(func=generate)

args = parser.parse_args()
if hasattr(args, 'func'):
    args.func(args)
